# Generated by Django 3.2.5 on 2021-07-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_highestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clisting_set', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuser_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
