# Generated by Django 3.2.5 on 2021-07-17 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=100, null=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wlisting_set', to='auctions.listing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wuser_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
